version: '3.9'

networks:

    hispaniola:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.20.0/24
        driver_opts:
            com.docker.network.bridge.name: hispaniola

    island:
        driver: bridge
        ipam:
            config:
                - subnet: 172.16.21.0/24
        driver_opts:
            com.docker.network.bridge.name: island

services:

    jim:
        image: alpine
        command: >
            sh -c "ip a &&
                   ip r &&
                   ping -w 5 -c 3 172.16.21.1 &&
                   ping -w 5 -c 3 172.16.21.2"
        networks:
            hispaniola:


    ben:
        image: alpine
        command: >
            sh -c "sleep 2 &&
                   ip a &&
                   ip r &&
                   ping -w 5 -c 3 172.16.20.1 &&
                   ping -w 5 -c 3 172.16.20.2"
        networks:
            island:
